version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/private:/etc/ssl/private:ro    # Подключение приватного ключа
      - /etc/ssl/certs:/etc/ssl/certs:ro        # Подключение сертификата
    depends_on:
      - flask_app
      - bot

  flask_app:
    build:
      context: ./flask_app
    volumes:
      - ./shared_data:/app/shared_data          # Общий volume для данных
    environment:
      - DATA_FILE=/app/shared_data/data.json
    expose:
      - "5000"                                  # Приложение будет доступно только через Nginx

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shared_data:/app/shared_data          # Общий volume для данных
    environment:
      - DATA_FILE=/app/shared_data/data.json
    expose:
      - "5000"                                  # Бот будет доступен только через Nginx

volumes:
  shared_data:
