version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/private:/etc/ssl/private:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    depends_on:
      - flask_app
      - bot

  flask_app:
    build:
      context: ./flask_app
    volumes:
      - ./shared_data:/app/shared_data
    environment:
      - DATA_FILE=/app/shared_data/data.json
    env_file:
      - .env
    expose:
      - "5000"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./shared_data:/app/shared_data
    environment:
      - DATA_FILE=/app/shared_data/data.json
    env_file:
      - .env
    expose:
      - "5000"

volumes:
  shared_data:
