version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    env_file:
      - bot/.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  bot:
    build:
      context: .
    container_name: telegram_bot
    env_file:
      - bot/.env
    depends_on:
      - minio

volumes:
  minio_data:
