name: Deploy to Server

on:
  push:
    branches:
      - main  # Срабатывает только на ветке main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используется виртуальная машина Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонирование репозитория

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.0  # Копирование файлов на сервер через SCP
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/mnt/volume1/scripts/masha_bot"

    - name: Restart Docker containers
      uses: appleboy/ssh-action@v0.1.0  # Выполнение команд на сервере через SSH
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /mnt/volume1/scripts/masha_bot
          docker-compose down
          docker-compose up --build -d
