name: Deploy to Server

on:
  push:
    branches:
      - main  # Срабатывает только на ветке main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используется виртуальная машина Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонирование репозитория
    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Pull latest changes and restart containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /mnt/volume1/scripts/masha_bot
          git pull origin main
          docker compose down
          docker compose up --build -d
